import type { Metadata } from "next";
import { Archivo, Cabin, Raleway } from "next/font/google";
import "./globals.css";


const archivo = Archivo({
  subsets: ["latin"],
  variable: "--font-archivo",
});

const cabin = Cabin({
  subsets: ["latin"],
  variable: "--font-cabin",
});

const raleway = Raleway({
  subsets: ["latin"],
  variable: "--font-raleway",
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${cabin.variable} ${archivo.variable} ${raleway.variable}`}
      >
        {children}
      </body>
    </html>
  );
}
